### ISSUE TITLE
Cant get it start - AttributeError: module 'cv2.cv2' has no attribute 'bgsegm'

### ISSUE THREAD

**Issue by connectnet** [pliablepixels/zmMagik#10]
Hi again!
I cant fix this error. Can you help me please? ♥
```
python3 ./magik.py --monitor=2 --eventid 1968 --blend -c config.ini
Traceback (most recent call last):
  File "./magik.py", line 198, in <module>
    if g.args['blend']: zmm_blend.blend_init()
  File "/zmMagik/zmMagik_helpers/blend.py", line 41, in blend_init
    det =  FgBg.DetectBackground(min_accuracy = g.args['threshold'], min_blend_area=g.args['minblendarea'])
  File "/zmMagik/zmMagik_helpers/detect_background.py", line 24, in __init__
    self.fgbg = cv2.bgsegm.createBackgroundSubtractorMOG(history=self.history, nmixtures=5, backgroundRatio=0.7, noiseSigma=0) 
AttributeError: module 'cv2.cv2' has no attribute 'bgsegm'
```

**Comment by pliablepixels** [comment]
Try
`sudo pip3 install opencv-contrib-python`

**Comment by connectnet** [comment]
Sorry, same error again.

**Comment by pliablepixels** [comment]
which version of OpenCV are you using?

**Comment by connectnet** [comment]
```
$ pip3 show  opencv-contrib-python
Name: opencv-contrib-python
Version: 4.1.2.30

Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: None
Author-email: None
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: numpy
Required-by: 
```
If I uncomment the line 26 in /zmMagik_helpers/detect_background.py it starts:
`self.fgbg = cv2.createBackgroundSubtractorMOG2(detectShadows=False, history=self.history) `

**Comment by pliablepixels** [comment]
Yes, use that. I think that is the new way. I'll check to see if that works for me too and modify accordingly.

**Comment by connectnet** [comment]
`sudo python3 ./magik.py -c config.ini --eventid xxxx --annotate --drawboxes=True
`
Works now, but the detecion is not correct. Ill try to change the paramerters.
Thanks for your support. :+1:

**Comment by pliablepixels** [comment]
When you say detection is not correct, what does it mean?

**Comment by connectnet** [comment]
It means, that we have some airplanes in the the street and a car is detected as an person or bicycle.

**Comment by connectnet** [comment]
Strange. In config.ini the detect_pattern selected only

`detectpattern = (person|car|motorbike|bus|truck|boat)`

and thats the result:

![Bildschirmfoto von 2020-02-02 12-11-57](https://user-images.githubusercontent.com/8360383/73607420-25dfa680-45b6-11ea-8706-23f0cffb0e0f.png)

**Comment by pliablepixels** [comment]
Which weights are you using? Yolo or tinyyolo?

**Comment by connectnet** [comment]
You mean the detection type?

`detection_type=mixed`

**Comment by pliablepixels** [comment]
No `weights_file` and `config_file`

**Comment by connectnet** [comment]
I didn't change anything. 
```
# you need these if you use yolo or mixed for detection
config_file=/var/lib/zmeventnotification/models/yolov3/yolov3.cfg
weights_file=/var/lib/zmeventnotification/models/yolov3/yolov3.weights
```

**Comment by connectnet** [comment]
I have to say, that I dont use the GPU acceleration. May be there is a correlation between the bad detection.

**Comment by pliablepixels** [comment]
I'll test in in the next few days.

**Comment by pliablepixels** [comment]
fixed in master

**Comment by connectnet** [comment]
Here the result from the new master:
```
$ sudo python3 ./magik.py -c config.ini --eventid 20314 --annotate --drawboxes=True
Background subtraction initialized
Traceback (most recent call last):
  File "./magik.py", line 208, in <module>
    if g.args['annotate']: zmm_annotate.annotate_init()
  File "/home/user1/Downloads/zmMagik-master/zmMagik_helpers/annotate.py", line 51, in annotate_init
    labelsPath =  g.args['labels_file'] )
TypeError: __init__() got an unexpected keyword argument 'darknetLib'
```

**Comment by pliablepixels** [comment]
Whoops sorry, did not fix annotate. Stay tuned.

**Comment by pliablepixels** [comment]
1. Fixed the annotate error
2. Note that you likely installed OpenCV via `pip` - that does not include the `bgsegm` libraries. I've  handled that error in the code and switch to the other API if its missing. Ideally, I'm [now recommending](https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html#opencv-install) everyone to just compile OpenCV from source, but if you don't have a GPU it may not be worth the time.

**Comment by connectnet** [comment]
Works now and detects right.
Thanks again for programming this great software.
