### ISSUE TITLE
Runtime error when using Yolo and non-GPU

### ISSUE THREAD

**Issue by neillbell** [pliablepixels/zmMagik#5]
The detect function in detect_yolo.py is generating an error when GPU is not used. I'm sorry, but I don't understand your code well enough to figure this out myself. Here is the output:
[output.txt](https://github.com/pliablepixels/zmMagik/files/3352237/output.txt)

**Comment by hawkeye217** [comment]
Not using a GPU and I have the same error...  Where should `label` be defined?

**Comment by pliablepixels** [comment]
fixed. Sorry, not sure why I never received a notification for this issue

**Comment by pliablepixels** [comment]
closing - assuming this is fixed. please reopen if you continue to see issues
