### ISSUE TITLE
Is there simple way just get video for period?

### ISSUE THREAD

**Issue by LuxoftAKutsan** [pliablepixels/zmMagik#6]
Is there a simple way just get the video for a certain period? 

Without annotations, without object recognition, etc ... 
With the possibility to specify result video duration. For example, one day in 5 minutes. 
I tried : 
`./magik.py --monitors=1 --from "yesterday, 0am" --to "today, 10am"  -c config.ini`

And the issues that I can see : 
 - There are annotations of date time on moving projects. 
 - Quality of video is worth than on zoneminder event.

**Comment by pliablepixels** [comment]
This is meant to be a video annotation tool. If you are looking simply to extract video for a period, you should get the video files directly from ZM.
