### ISSUE TITLE
Segmentation fault due to change in the darknet detection structure

### ISSUE THREAD

**Issue by neillbell** [pliablepixels/zmMagik#7]
That latest version of  AlexeyAB/darknet  has apparently changed the detection structure that it uses and zmMagik has not been updated to reflect this.

The simpleYolo.py file in zmMagik currently defines the DETECTION class as:
```
class DETECTION(Structure):
    _fields_ = [("bbox", BOX),
                ("classes", c_int),
                ("prob", POINTER(c_float)),
                ("mask", POINTER(c_float)),
                ("objectness", c_float),
                ("sort_class", c_int)]
```
but darknet.h defines the detection structure as:
```
typedef struct detection{
    box bbox;
    int classes;
    float *prob;
    float *mask;
    float objectness;
    int sort_class;
    float *uc; // Gaussian_YOLOv3 - tx,ty,tw,th uncertainty
    int points; // bit-0 - center, bit-1 - top-left-corner, bit-2 - bottom-right-corner
} detection;
```
The DETECTION class is missing the uc and points fields.

I have updated the DETECTION class and zmMagik works correctly. If this sounds right, I can do a PR.

**Comment by pliablepixels** [comment]
I wonder if we should do this conditionally depending on the darknet version? 
I assume this would be a breaking change.

(On travel till end of this month, responses will be slow)

**Comment by neillbell** [comment]
It looks like the version numbers did not change at the time the structure change was committed. Also, there doesn't seem to be a way to query the darknet version programmatically.

**Comment by pliablepixels** [comment]
The good news is that it looks like OpenCV now supports GPU for DNNs 4.2 so I can do away with direct darknet integration. I'll look into it once I am back but in the mean time please feel free to do a PR

**Comment by neillbell** [comment]
That's true, but the OpenCV DNN only supports compute capability >=5.3 and my GPU is only 3.0.

I suppose I need to get a new GPU. This one was free.

**Comment by pliablepixels** [comment]
Ok, in that case maybe we add a note in the PR in logs saying 'If you get a seg fault, you need to update Darknet libs to XX/YY date

**Comment by neillbell** [comment]
Will do. I think I'll add something to the FAQ, also.
